### ISSUE TITLE
Favicons on the dev server are broken

### ISSUE THREAD

**Issue by SoullessWaffle** [ProjectTimato/timato-client-web#1]
Steps to reproduce:
1. `$ npm run watch -s`
2. Once the page has loaded, open the dev console and inspect the icon elements in the head. If you try to visit their `href`s, you get a `404`.
3. Also observe that the tab has no favicon.

**Comment by junedev** [comment]
The backend is not serving any assets yet. I will take care of this.

**Comment by SoullessWaffle** [comment]
@junedev the client-web repo has [its own dev server](https://github.com/ProjectTimato/timato-client-web/blob/bc8d8f97b8578be1089946d6a9e1637d4d1b1518/gulpfile.js#L22-L49) for development so we don't rely on the backend while developing the client. Sorry for the confusion.
